"""add ua_mode to providers

Revision ID: 82318fbd2666
Revises: 81a544f7b657
Create Date: 2026-07-13 09:39:59.957549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82318fbd2666'
down_revision = '81a544f7b657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ua_mode', sa.String(length=32), server_default='auto', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('ua_mode')

    # ### end Alembic commands ###
